import Head from 'next/head';
import Image from 'next/image';
import { Box } from '@mui/material';
import { memo } from 'react';
import PageContainer from '../Components/PageContainer';
import HomeSignin from '../Views/HomeView/HomeSignin';

const Home = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <PageContainer pageTitle={'Admin Sign In'}>
          <HomeSignin />
        </PageContainer>
      </Box>
    </div>
  )
}

export default memo(Home);