import Head from 'next/head';
import Image from 'next/image';
import { Box } from '@mui/material';
import { memo } from 'react';

const Home = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Final Project Admin Pannel
        </h1>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export default memo(Home);